{
 "title": "Mining",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc offset 0 limit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select height as \"Height\" \nfrom cc_getblockstats \norder by height desc \noffset 1\nlimit 1;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc offset 2 limit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc offset 3 limit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc offset 4 limit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc offset 5 limit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
    },
    { "expression": "($G-$F)/1000", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 1 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 1 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 1 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 1 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 1 LIMIT 1;\n"
    },
    { "expression": "($G-$F)/1000", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 2 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 2 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 2 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 2 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 2 LIMIT 1;\n"
    },
    { "expression": "($G-$F)/1000", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 3 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 3 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 3 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 3 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 3 LIMIT 1;\n"
    },
    { "expression": "($G-$F)/1000", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 4 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 4 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 4 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 4 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 4 LIMIT 1;\n"
    },
    { "expression": "($G-$F)/1000", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 5 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 5 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 5 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 5 LIMIT 1;\n"
    },
    {
     "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 5 LIMIT 1;\n"
    },
    { "expression": "($G-$F)/1000", "type": "math" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "rawSql": "select pool from cc_getblockpool order by height desc offset 1 limit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "rawSql": "select pool from cc_getblockpool order by height desc offset 3 limit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "rawSql": "select pool from cc_getblockpool order by height desc offset 4 limit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "rawSql": "select pool from cc_getblockpool order by height desc offset 5 limit 1;"
    }
   ]
  },
  {
   "title": "Price : Hashrate : Difficulty ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \"time\" as \"Time\", value as \"Hashrate\" FROM cm_btc_hashrate_1d;"
    },
    {
     "rawSql": "SELECT \"time\" as \"Time\", value as \"Difficulty\" FROM cm_difflast_1d;"
    },
    {
     "rawSql": "SELECT \"time\", value as \"Price\" FROM cm_btc_price_usd_1d;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <video controls autoplay loop style=\"width: auto%; height: auto;\">\n        <source src=\"https://clarionchain.io/images/mining_pow.m4v\" type=\"video/mp4\">\n    </video>\n</div>\n"
   }
  },
  {
   "type": "table",
   "description": "Avg block time is for the current subsidy epoch. ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH Epochs AS (\n    SELECT\n        \"time\",\n        height,\n        FLOOR((height - 1) / 2016) AS epoch\n    FROM\n        cc_getblockstats\n    ORDER BY\n        height\n),\nEpochIntervals AS (\n    SELECT\n        epoch,\n        MIN(\"time\") AS start_time,\n        MAX(\"time\") AS end_time,\n        MIN(height) AS start_block,\n        MAX(height) AS current_block,\n        COUNT(*) AS block_count\n    FROM\n        Epochs\n    GROUP BY\n        epoch\n),\nCurrentEpoch AS (\n    SELECT\n        MAX(epoch) AS current_epoch\n    FROM\n        Epochs\n),\nCurrentEpochDetails AS (\n    SELECT\n        (ei.end_time - ei.start_time) / (ei.block_count - 1) AS avg_block_time\n    FROM\n        EpochIntervals ei\n    INNER JOIN\n        CurrentEpoch ce ON ei.epoch = ce.current_epoch\n)\nSELECT\n    avg_block_time\nFROM\n    CurrentEpochDetails;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH CurrentHeightInfo AS (\n  SELECT\n    MAX(height) AS current_height\n  FROM\n    cc_getblockstats\n),\nHalvingInfo AS (\n  SELECT\n    current_height,\n    ((FLOOR(current_height / 210000) + 1) * 210000) - current_height AS \"blocks_until_halving\"\n  FROM\n    CurrentHeightInfo\n),\nTimeUntilHalving AS (\n  SELECT\n    current_height,\n    blocks_until_halving,\n    blocks_until_halving * 10 * 60 AS \"time_until_halving_seconds\" -- 10 minutes per block in seconds\n  FROM\n    HalvingInfo\n)\nSELECT\n  TO_TIMESTAMP(\n    EXTRACT(\n      EPOCH\n      FROM\n        NOW()\n    ) + time_until_halving_seconds\n  ) AS Halving_Estimate\nFROM\n  TimeUntilHalving;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "cc_hashrate", "legendFormat": "__auto" },
    {
     "rawSql": "WITH Epochs AS (\n    SELECT\n        \"time\",\n        height,\n        FLOOR((height - 1) / 2016) AS epoch\n    FROM\n        cc_getblockstats\n    ORDER BY\n        height\n),\nEpochIntervals AS (\n    SELECT\n        epoch,\n        MIN(\"time\") AS start_time,\n        MAX(\"time\") AS end_time,\n        MIN(height) AS start_block,\n        MAX(height) AS current_block,\n        COUNT(*) AS block_count\n    FROM\n        Epochs\n    GROUP BY\n        epoch\n),\nCurrentEpoch AS (\n    SELECT\n        MAX(epoch) AS current_epoch\n    FROM\n        Epochs\n),\nCurrentEpochDetails AS (\n    SELECT\n        (ei.end_time - ei.start_time) / (ei.block_count - 1) AS \"Avg Block Time\"\n    FROM\n        EpochIntervals ei\n    INNER JOIN\n        CurrentEpoch ce ON ei.epoch = ce.current_epoch\n)\nSELECT\n    \"Avg Block Time\"\nFROM\n    CurrentEpochDetails;\n"
    },
    { "expression": "$D-$C", "type": "math" },
    {
     "rawSql": "SELECT \"time\", difficulty as \"Difficulty\" FROM cc_getblockchaininfo order by time desc limit 1;"
    }
   ]
  },
  {
   "title": "Halving Epoch",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH CurrentHeightInfo AS (\n    SELECT MAX(height) AS current_height FROM cc_getblockstats\n),\nHalvingEpochInfo AS (\n    SELECT\n        current_height,\n        FLOOR(current_height / 210000) AS current_epoch,\n        FLOOR(current_height / 210000) * 210000 AS start_of_current_epoch,\n        (FLOOR(current_height / 210000) + 1) * 210000 AS start_of_next_epoch\n    FROM\n        CurrentHeightInfo\n),\nEpochProgress AS (\n    SELECT\n        current_height,\n        current_epoch,\n        start_of_current_epoch,\n        start_of_next_epoch,\n        (current_height - start_of_current_epoch) AS blocks_into_current_epoch,\n        start_of_next_epoch - start_of_current_epoch AS blocks_per_epoch,\n        ((current_height - start_of_current_epoch) / (start_of_next_epoch - start_of_current_epoch)::float) * 100 AS percent_complete\n    FROM\n        HalvingEpochInfo\n)\nSELECT\n    current_epoch + 1 AS halving_epoch, -- Adjusting epoch numbering to start from 1\n    TRUNC((percent_complete * 100) + 0.5) / 100 AS percent_complete -- Manual rounding to 2 decimal places\nFROM\n    EpochProgress;\n"
    }
   ]
  },
  {
   "title": "Difficulty Epoch ",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH epoch_details AS (\n    SELECT\n        MAX(height) % 2016 AS blocks_into_epoch,\n        2016 AS epoch_length\n    FROM\n        cc_getblockstats\n)\nSELECT\n    (CAST(blocks_into_epoch AS FLOAT) / epoch_length) * 100 AS percentage_complete\nFROM\n    epoch_details;\n"
    }
   ]
  },
  { "title": "More", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": {
    "content": "Bitcoin targets 10 min block intervals.  \nA new block is mined every 10 min on avg.  \nMore hashrate causes blocks to be mined faster.  \nLess hashrate causes blocks to be mined slower.  \n\n"
   }
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 106 },
     "targets": [
      {
       "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 106 },
     "targets": [
      {
       "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 106 },
     "targets": [
      {
       "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 106 },
     "targets": [
      {
       "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 106 },
     "targets": [
      {
       "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 106 },
     "targets": [
      {
       "rawSql": "select pool from cc_getblockpool order by height desc limit 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "rawSql": "select * from cc_getblockstats order by height desc limit 6;"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 105 },
     "options": {
      "content": "Hashrate is the compute strength of the Bitcoin network. Measured as hashes per second HS/s"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 108 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT height as \"Height\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  avgfeerate as \"sat/vB\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT txs as \"Txs\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT totalfee/100000000.0 as \"Fees\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT total_size as \"Block Size\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      {
       "rawSql": "SELECT  \"time\"*1000 as \"Block Time\" FROM cc_getblockstats order by height desc offset 0 LIMIT 1;\n"
      },
      { "expression": "($G-$F)/1000", "type": "math" }
     ]
    },
    {
     "title": "Pools Blocks Mined (broken)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "rawSql": "SELECT \n    height, \n    TO_TIMESTAMP(block_timestamp) AS block_timestamp, \n    pool \nFROM \n    cc_getblockpool \nORDER BY \n    height DESC;\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 115 },
     "targets": [
      {
       "rawSql": "select height as \"Height\" from cc_getblockstats order by height desc limit 1;"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 121 },
     "options": {
      "content": "\n\nBLock rewards (subsidy + fees) paid to miners\n\n"
     }
    }
   ]
  }
 ]
}