{
 "title": "Market",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(price_coinbase + price_kraken)/2",
     "legendFormat": "__auto"
    },
    {
     "rawSql": "SELECT MAX(value) AS \"All Time High\" FROM cm_btc_price_usd_1d;\n"
    },
    { "expression": "$A*21000000", "type": "math" },
    {
     "rawSql": "SELECT \"time\", value as \"Realized Cap\" FROM cm_realized_cap_1d order by time desc limit 1;"
    },
    { "expression": "(1 / $A) * 100000000", "type": "math" }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"BTC:USD\" FROM cm_btc_price_usd_1d;\n"
    }
   ]
  },
  {
   "title": "Market Cap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"BTC:USD\" FROM cm_market_cap_current_1d;\n"
    }
   ]
  },
  {
   "title": "Realized Cap",
   "type": "timeseries",
   "description": "Cost basis",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"BTC:USD\" FROM cm_realized_cap_1d ;\n"
    }
   ]
  },
  {
   "title": "1 Day Oscillator",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value as \"CapMrktCurUSD\" FROM cm_market_cap_current_1d "
    },
    {
     "rawSql": "SELECT \"time\", value as \"CapRealUSD\" FROM cm_realized_cap_1d "
    },
    {
     "rawSql": "WITH btc_market_cap_diff_data AS (\n  SELECT\n    \"time\",\n    \"value\" - LAG(\"value\", 1) OVER (ORDER BY \"time\") AS btc_market_cap_diff\n  FROM cm_market_cap_current_1d\n),\nrealized_market_cap_data AS (\n  SELECT\n    \"time\",\n    \"value\" AS realized_market_cap\n  FROM cm_realized_cap_1d\n),\nrealized_market_cap_diff_data AS (\n  SELECT\n    \"time\",\n    realized_market_cap - LAG(realized_market_cap, 1) OVER (ORDER BY \"time\") AS realized_market_cap_diff\n  FROM realized_market_cap_data\n),\ndelta_data AS (\n  SELECT\n    b.\"time\",\n    b.btc_market_cap_diff - r.realized_market_cap_diff AS delta\n  FROM btc_market_cap_diff_data b\n  JOIN realized_market_cap_diff_data r ON b.\"time\" = r.\"time\"\n)\nSELECT\n  \"time\",\n  CASE\n    WHEN STDDEV(delta) OVER (ORDER BY \"time\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) = 0 THEN NULL\n    ELSE (delta - AVG(delta) OVER (ORDER BY \"time\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW))\n         / STDDEV(delta) OVER (ORDER BY \"time\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)\n  END AS gradient\nFROM delta_data;\n"
    }
   ]
  },
  {
   "title": "Mayer Multiple",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Price\" from cm_btc_price_usd_1d ;"
    },
    {
     "rawSql": "SELECT\n    \"time\",\n    AVG(value) OVER (ORDER BY \"time\" ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS \"200 Day Moving Average\"\nFROM\n    cm_btc_price_usd_1d;\n"
    },
    { "expression": "2.5*$B", "type": "math" },
    { "expression": "1.7*$B", "type": "math" },
    { "expression": "1.1*$B", "type": "math" },
    { "expression": ".55*$B", "type": "math" }
   ]
  }
 ]
}