{
 "title": "Home",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; background-color: rgb(17, 18, 23); width: 100%; height: 100%; margin: 0; padding: 0;\">\n    <img src=\"https://clarionchain.io/images/clearmined_v2.png\" alt=\"Logo\" style=\"width: 40px; height: 40px; margin-left: 10px;\">\n    <div style=\"margin-left: 10px;\">\n        <h1 style=\"font-size: 15px; color: rgb(87, 148, 242); margin: 0;\">ClarionChain</h1>\n        <h1 style=\"font-size: 15px; color: rgb(87, 148, 242); margin: 0;\">Bitcoin</h1>\n    </div>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 3, "y": 0 },
   "options": {
    "content": "<div style=\"background-color: rgb(17, 18, 23); padding: 5px;\">\n  <a href=\"http://clarionchain.io\" style=\"color: rgb(87, 148, 242); text-decoration: none; margin-right: 20px;\">ClarionChain.io</a>\n  <a href=\"http://clarionchain.io\" style=\"color: rgb(87, 148, 242); text-decoration: none; margin-right: 20px;\">Market</a>\n  <a href=\"http://clarionchain.io\" style=\"color: rgb(87, 148, 242); text-decoration: none; margin-right: 20px;\">Fees</a>\n  <a href=\"http://clarionchain.io\" style=\"color: rgb(87, 148, 242); text-decoration: none; margin-right: 20px;\">Supply</a>\n  <a href=\"http://clarionchain.io\" style=\"color: rgb(87, 148, 242); text-decoration: none; margin-right: 20px;\">Blockstats</a>\n  <a href=\"http://clarionchain.io\" style=\"color: rgb(87, 148, 242); text-decoration: none; margin-right: 20px;\">Mining</a>\n  <a href=\"http://clarionchain.io\" style=\"color: rgb(87, 148, 242); text-decoration: none;\">UTXOs</a>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; background-color: rgb(17, 18, 23); width: 100%; height: 100%; margin: 0; padding: 0; overflow: hidden;\">\n    <!-- Scrolling content -->\n    <div style=\"animation: scroll 20s linear infinite; white-space: nowrap;\">\n        <!-- Replace these placeholders with your real data -->\n        <!--<span style=\"color: yellow;\">Resources:</span> -->\n        <a href=\"https://bobspaces.net\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">BOBspaces.net</a>\n        <a href=\"https://bitcoin.clarkmoody.com/dashboard/\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">ClarkMoody.com</a>\n        <a href=\"https://timechainstats.com\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">Timechainstats.com</a>\n        <a href=\"https://timechaincalendar.com\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">Timechaincalendar.com</a>\n        <a href=\"https://bitbo.io/\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">Bitbo.com</a>\n        <a href=\"https://bitnodes.io/\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">Bitnodes.io</a>\n        <a href=\"https://mempool.space\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">Mempool.space</a>\n        <a href=\"https://learnmeabitcoin.com/\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">LearnMeBitcoin.com</a>\n        <a href=\"https://stackernews.com/\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">StackerNews.com</a>\n        <a href=\"https://www.lopp.net/bitcoin-information.html\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">Lopp.net</a>\n         <a href=\"https://bits.monospace.live/\" target=\"_blank\" style=\"color: rgb(87, 148, 242); margin-left: 20px;\">Bitfeed.live</a>\n    </div>\n</div>\n\n<style>\n@keyframes scroll {\n    0% {\n        transform: translateX(50%);\n    }\n    100% {\n        transform: translateX(-100%);\n    }\n}\n</style>\n\n"
   },
   "targets": [
    { "rawSql": "select * from resources ;\n" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n  #rss-feed-container {\n    display: flex;\n    align-items: center;\n    background-color: rgb(17, 18, 23);\n    width: 100%;\n    height: 100%;\n    margin: 0;\n    padding: 0;\n    overflow: hidden;\n  }\n  #rss-feed {\n    animation: scroll 60s linear infinite;\n    white-space: nowrap;\n  }\n  .rss-item {\n    color: rgb(87, 148, 242);\n    margin-left: 20px;\n    text-decoration: none;\n  }\n  @keyframes scroll {\n    0% { transform: translateX(50%); }\n    100% { transform: translateX(-100%); }\n  }\n</style>\n</head>\n<body>\n<div id=\"rss-feed-container\">\n  <div id=\"rss-feed\">\n    Loading feed...\n  </div>\n</div>\n\n<script>\n  async function fetchRSSFeed() {\n    try {\n      const response = await fetch('https://rss.app/feeds/tkRoYp11F7wrQoIp.xml');\n      const text = await response.text();\n      const parser = new DOMParser();\n      const xmlDoc = parser.parseFromString(text, \"text/xml\");\n\n      const items = xmlDoc.getElementsByTagName('item');\n      let html = '';\n      for (let i = 0; i < items.length; i++) {\n        const title = items[i].getElementsByTagName('title')[0].textContent;\n        const link = items[i].getElementsByTagName('link')[0].textContent;\n        html += `<a class=\"rss-item\" href=\"${link}\" target=\"_blank\">${title}</a>`;\n      }\n\n      document.getElementById('rss-feed').innerHTML = html;\n\n      // Start the animation immediately after the content is loaded\n      document.getElementById('rss-feed').style.animationPlayState = 'running';\n    } catch (error) {\n      document.getElementById('rss-feed').innerHTML = 'Failed to load feed';\n      console.error('Error loading the RSS feed:', error);\n    }\n  }\n\n  fetchRSSFeed();\n</script>\n</body>\n</html>\n"
   },
   "targets": [
    { "rawSql": "select * from resources ;\n" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT height as \"Block\", pool as \"Pool\" FROM cc_getblockpool ORDER BY height DESC LIMIT 1;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH CurrentHeightInfo AS (\n  SELECT\n    MAX(height) AS current_height\n  FROM\n    cc_getblockstats\n),\nHalvingInfo AS (\n  SELECT\n    current_height,\n    ((FLOOR(current_height / 210000) + 1) * 210000) - current_height AS \"blocks_until_halving\"\n  FROM\n    CurrentHeightInfo\n),\nTimeUntilHalving AS (\n  SELECT\n    current_height,\n    blocks_until_halving,\n    blocks_until_halving * 10 * 60 AS \"time_until_halving_seconds\" -- 10 minutes per block in seconds\n  FROM\n    HalvingInfo\n)\nSELECT\n  TO_TIMESTAMP(\n    EXTRACT(\n      EPOCH\n      FROM\n        NOW()\n    ) + time_until_halving_seconds\n  ) AS Halving_Estimate\nFROM\n  TimeUntilHalving;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(price_coinbase + price_kraken)/2",
     "legendFormat": "__auto"
    },
    {
     "rawSql": "SELECT MAX(value) AS \"All Time High\" FROM cm_btc_price_usd_1d;\n"
    },
    { "expression": "$A*21000000", "type": "math" },
    {
     "rawSql": "SELECT \"time\", value as \"Realized Cap\" FROM cm_realized_cap_1d order by time desc limit 1;"
    },
    { "expression": "(1 / $A) * 100000000", "type": "math" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "cc_hashrate", "legendFormat": "__auto" },
    {
     "rawSql": "WITH Epochs AS (\n    SELECT\n        \"time\",\n        height,\n        FLOOR((height - 1) / 2016) AS epoch\n    FROM\n        cc_getblockstats\n    ORDER BY\n        height\n),\nEpochIntervals AS (\n    SELECT\n        epoch,\n        MIN(\"time\") AS start_time,\n        MAX(\"time\") AS end_time,\n        MIN(height) AS start_block,\n        MAX(height) AS current_block,\n        COUNT(*) AS block_count\n    FROM\n        Epochs\n    GROUP BY\n        epoch\n),\nCurrentEpoch AS (\n    SELECT\n        MAX(epoch) AS current_epoch\n    FROM\n        Epochs\n),\nCurrentEpochDetails AS (\n    SELECT\n        (ei.end_time - ei.start_time) / (ei.block_count - 1) AS \"Avg Block Time\"\n    FROM\n        EpochIntervals ei\n    INNER JOIN\n        CurrentEpoch ce ON ei.epoch = ce.current_epoch\n)\nSELECT\n    \"Avg Block Time\"\nFROM\n    CurrentEpochDetails;\n"
    },
    { "expression": "$D-$C", "type": "math" },
    {
     "rawSql": "SELECT \"time\", difficulty as \"Difficulty\" FROM cc_getblockchaininfo order by time desc limit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(subsidy)/100000000.0 AS \"Total Bitcoin Mined\"\nFROM\n  cc_getblockstats;\n"
    },
    { "expression": "$A/21000000", "type": "math" },
    {
     "rawSql": "SELECT txouts \"UTXO Count\" FROM cc_gettxsetoutinfo order by height desc limit 1;"
    },
    {
     "rawSql": "SELECT transactions as \"Txs in UTXO Set\" FROM cc_gettxsetoutinfo order by height desc limit 1;"
    },
    {
     "rawSql": "SELECT disk_size \"UTXO Set Size on Disk\" FROM cc_gettxsetoutinfo order by height desc limit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", height as \"Height\" FROM cc_getblockstats order by height desc limit 1;"
    },
    {
     "rawSql": "WITH CurrentHeight AS (\n    SELECT MAX(height) AS current_height FROM cc_getblockstats\n)\nSELECT\n    FLOOR(current_height / 210000)+1 AS \"Epoch\"\nFROM\n    CurrentHeight;"
    },
    {
     "rawSql": "SELECT\n  \"time\",\n  ROUND(subsidy/100000000.0, 3) AS \"Subsidy\"\nFROM\n  cc_getblockstats\nORDER BY\n  height DESC\nLIMIT 1;\n"
    },
    {
     "rawSql": "WITH CurrentHeight AS (\n    SELECT MAX(height) AS current_height FROM cc_getblockstats\n),\nHalvingInfo AS (\n    SELECT\n        current_height,\n        FLOOR((current_height / 210000) + 1) * 210000 AS next_halving_height\n    FROM\n        CurrentHeight\n)\nSELECT\n    next_halving_height - current_height AS \"Blocks to Halving\"\nFROM\n    HalvingInfo;\n"
    }
   ]
  },
  {
   "title": "Price % of All Time High",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "% Supply Mined",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/21000000", "type": "math" }
   ]
  },
  {
   "title": "Halving Epoch",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH CurrentHeightInfo AS (\n    SELECT MAX(height) AS current_height FROM cc_getblockstats\n),\nHalvingEpochInfo AS (\n    SELECT\n        current_height,\n        FLOOR(current_height / 210000) AS current_epoch,\n        FLOOR(current_height / 210000) * 210000 AS start_of_current_epoch,\n        (FLOOR(current_height / 210000) + 1) * 210000 AS start_of_next_epoch\n    FROM\n        CurrentHeightInfo\n),\nEpochProgress AS (\n    SELECT\n        current_height,\n        current_epoch,\n        start_of_current_epoch,\n        start_of_next_epoch,\n        (current_height - start_of_current_epoch) AS blocks_into_current_epoch,\n        start_of_next_epoch - start_of_current_epoch AS blocks_per_epoch,\n        ((current_height - start_of_current_epoch) / (start_of_next_epoch - start_of_current_epoch)::float) * 100 AS percent_complete\n    FROM\n        HalvingEpochInfo\n)\nSELECT\n    current_epoch + 1 AS halving_epoch, -- Adjusting epoch numbering to start from 1\n    TRUNC((percent_complete * 100) + 0.5) / 100 AS percent_complete -- Manual rounding to 2 decimal places\nFROM\n    EpochProgress;\n"
    }
   ]
  },
  {
   "title": "Difficulty Epoch ",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH epoch_details AS (\n    SELECT\n        MAX(height) % 2016 AS blocks_into_epoch,\n        2016 AS epoch_length\n    FROM\n        cc_getblockstats\n)\nSELECT\n    (CAST(blocks_into_epoch AS FLOAT) / epoch_length) * 100 AS percentage_complete\nFROM\n    epoch_details;\n"
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value as \"Price Daily\" FROM cm_btc_price_usd_1d order by time; "
    }
   ]
  },
  {
   "title": "Fees : Avg Fee/vByte",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", avgfeerate as \"AvgFeeRate\" FROM cc_getblockstats order by height desc limit 144;"
    }
   ]
  },
  {
   "title": "Block Size : Daily Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', TO_TIMESTAMP(\"time\")) AS day,\n  AVG(total_size) AS \"Average Block Size\"\nFROM\n  cc_getblockstats\nGROUP BY\n  DATE_TRUNC('day', TO_TIMESTAMP(\"time\"))\nORDER BY\n  day;\n"
    }
   ]
  },
  {
   "title": "Block Interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp(\"time\") AS \"Time\",\n  EXTRACT(EPOCH FROM (to_timestamp(\"time\") - LAG(to_timestamp(\"time\")) OVER (ORDER BY height))) AS \"Interval\"\nFROM\n  cc_getblockstats\nORDER BY\n  height DESC\nLIMIT 144;\n"
    }
   ]
  },
  {
   "title": "Block Rewards : Subsidy + Fees",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", (totalfee/100000000.0) as \"Fees\" FROM cc_getblockstats order by height desc limit 1;"
    },
    {
     "rawSql": "SELECT (subsidy/100000000.0) as \"Subsidy\" FROM cc_getblockstats order by height desc limit 1;"
    }
   ]
  },
  {
   "title": "Price : Hashrate : Difficulty ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \"time\" as \"Time\", value as \"Hashrate\" FROM cm_btc_hashrate_1d;"
    },
    {
     "rawSql": "SELECT \"time\" as \"Time\", value as \"Hashrate\" FROM cm_btc_hashrate_1d;"
    },
    {
     "rawSql": "SELECT \"time\" as \"Time\", value as \"Difficulty\" FROM cm_difflast_1d;"
    },
    {
     "rawSql": "SELECT \"time\", value as \"Price\" FROM cm_btc_price_usd_1d;"
    }
   ]
  },
  {
   "title": "1 Day Oscillator",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value as \"CapMrktCurUSD\" FROM cm_market_cap_current_1d "
    },
    {
     "rawSql": "SELECT \"time\", value as \"CapRealUSD\" FROM cm_realized_cap_1d "
    },
    {
     "rawSql": "WITH btc_market_cap_diff_data AS (\n  SELECT\n    \"time\",\n    \"value\" - LAG(\"value\", 1) OVER (ORDER BY \"time\") AS btc_market_cap_diff\n  FROM cm_market_cap_current_1d\n),\nrealized_market_cap_data AS (\n  SELECT\n    \"time\",\n    \"value\" AS realized_market_cap\n  FROM cm_realized_cap_1d\n),\nrealized_market_cap_diff_data AS (\n  SELECT\n    \"time\",\n    realized_market_cap - LAG(realized_market_cap, 1) OVER (ORDER BY \"time\") AS realized_market_cap_diff\n  FROM realized_market_cap_data\n),\ndelta_data AS (\n  SELECT\n    b.\"time\",\n    b.btc_market_cap_diff - r.realized_market_cap_diff AS delta\n  FROM btc_market_cap_diff_data b\n  JOIN realized_market_cap_diff_data r ON b.\"time\" = r.\"time\"\n)\nSELECT\n  \"time\",\n  CASE\n    WHEN STDDEV(delta) OVER (ORDER BY \"time\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) = 0 THEN NULL\n    ELSE (delta - AVG(delta) OVER (ORDER BY \"time\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW))\n         / STDDEV(delta) OVER (ORDER BY \"time\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)\n  END AS gradient\nFROM delta_data;\n"
    }
   ]
  }
 ]
}