version: '3.7'

services:
  grafana:
    image: clarionchain_perfect_version:latest
    container_name: clarionchain_docker
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana  # Store all Grafana data in the container volume
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_DATABASE_HOST=postgres_clarionchain_docker_host  # Database host
      - GF_DATABASE_USER_FILE=/run/secrets/postgres_clarionchain_docker_user  # Docker Secrets inject username here
      - GF_DATABASE_PASSWORD_FILE=/run/secrets/postgres_clarionchain_docker_password  # Docker Secrets inject password here
    secrets:
      - postgres_clarionchain_docker_user
      - postgres_clarionchain_docker_password
    restart: always

volumes:
  grafana_data:

secrets:
  postgres_clarionchain_docker_user:
    external: true
  postgres_clarionchain_docker_password:
    external: true
